### PR TITLE
Rebuilt version from v2.1

### PR DESCRIPTION
**Pull request by jief666**
Hi,

here my version. I've called it version 3 because it's really different from v 2.1

### CODE REVIEW

**Comment by maximelebreton** [comment]
hi @jief666, can you share a copy of the google sheet associated with your script?
thx!

**Comment by jief666** [comment]
Here it is : https://drive.google.com/open?id=1m9dt1tgTIg669lIVfU1AsWubcRzUsC5R2N65XdzeoYQ

**Comment by St3ph-fr** [comment]
Bonjour

Je vais tester et si ça passe je pousserai la version. Pas trop le temps de checker et reprendre tout le code.

Stéphane

**Comment by St3ph-fr** [comment]
J'ai partagé la version sur la page G+
https://plus.google.com/b/116856005769817085204/116856005769817085204/posts/8cky5nTFJyF

**Comment by jief666** [comment]
Ok, merci.

**Pull request closed without merging**
